### ISSUE TITLE
Please change your vendor name in packagist

### ISSUE THREAD

**Issue by harikt** [hipsterjazzbo/pubnub-laravel#1]
Hi, 

I have noticed the package https://packagist.org/packages/aura/pubnub-laravel which has nothing to do with aura.

Could you please take off the vendor name from the package, so all the @auraphp packages can stay on the same without any issues / confusions.

Thank you for considering

Hari KT

**Comment by cordoval** [comment]
:+1:

**Comment by stephenlb** [comment]
woh snazzy.

**Comment by fareesh** [comment]
Looks like it's been changed to auraeq
