### ISSUE TITLE
Name "Aura" Is Taken

### ISSUE THREAD

**Issue by pmjones** [hipsterjazzbo/pubnub-laravel#2]
Unless you want to be confused with the existing Aura for PHP project, you'll want to change the name. http://auraphp.com https://github.com/auraphp https://github.com/aura

Edit: The Aura project also already uses the "Aura\" vendor namespace.

**Comment by cordoval** [comment]
:+1: please @cfidecaro you could move to auraeq which reflects better your username

**Comment by pmjones** [comment]
Really, any portion using "Aura" adds the possibility for confusing the two projects.

**Comment by cordoval** [comment]
now that i see that even your company is different I beg you not use aura as @pmjones is stating

Thank you!

**Comment by hipsterjazzbo** [comment]
Absolutely! Apologies, I didn't realize it was taken.

**Comment by pmjones** [comment]
Not at all, sir -- hard to know the name of every project everywhere. Best wishes on your project!

**Comment by hipsterjazzbo** [comment]
Okay guys, I've renamed it to use the vendor `auraeq`. @pmjones, I agree that ideally there should be no overlap, but unfortunately that is our company name. If it's still a problem in future, I may consider choosing an entirely unrelated name (although I doubt whther there are many/any that are completely untouched).

Also, apparently there's no way to rename a package on packagist, so I've had to delete and re-add it. If anyone knows of a better way of doing it, I'd love to know :)

**Comment by cordoval** [comment]
is the only way

**Comment by pmjones** [comment]
>  apparently there's no way to rename a package on packagist

That's generally the way, although if you get Jordi on a good day he may grant you a favor of renaming it in place.

**Comment by pmjones** [comment]
Also, I have a bad name in the Laravel world, so if they see the word "aura*" in the vendor name you may get some freak-outs.

**Comment by hipsterjazzbo** [comment]
Ha well that's good to know.

TBH, I don't really care if anyone uses this. I just figured it took me so long to make some usable out of Pubnub's bullshit library that I may as well share.
